fix(home): remove corepack
error: 'corepack_latest' has been removed, use 'corepack.override {
nodejs = pkgs.nodejs_latest; }' instead.

No longer needed!